# Site settings
title: DeVoresyah Libraries
email: de.voresyah@gmail.com
description: All DeVoresyah Repository With Blog Content
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://DeVoresyah.github.io" # the base hostname & protocol for your site
twitter_username: DeVoresyah
github_username:  DeVoresyah

# Build settings
markdown: kramdown
paginate: 3
paginate_path: "/allpost/page/:num"
authors:
  devoresyah:
    name: DeVoresyah ArEst
    display_name: DeVoresyah
    email: de.voresyah@gmail.com
    web: http://devoresyah.github.io
    twitter: DeVoresyah
    github: DeVoresyah